<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Hierarchical clustering • bigPint</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png">
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/sandstone/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><!-- docsearch --><script src="../docsearch.js"></script><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/docsearch.js/2.6.3/docsearch.min.css" integrity="sha256-QOSRU/ra9ActyXkIBbiIB144aDBdtvXBcNc3OTNuX/Q=" crossorigin="anonymous">
<link href="../docsearch.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script><meta property="og:title" content="Hierarchical clustering">
<meta property="og:description" content="bigPint">
<meta property="og:image" content="http://lindsayrutter.github.io/bigPint/logo.png">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">bigPint</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">1.5.1</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home"></span>
     
  </a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fas fa fas fa-book"></span>
     
    Get Started
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/plotIntro.html">Introduction to bigPint plots</a>
    </li>
    <li>
      <a href="../articles/installation.html">Installation</a>
    </li>
    <li>
      <a href="../articles/data.html">Data object</a>
    </li>
    <li>
      <a href="../articles/dataMetrics.html">Data metrics object</a>
    </li>
    <li>
      <a href="../articles/summarizedExperiment.html">SummarizedExperiment object</a>
    </li>
    <li>
      <a href="../articles/static.html">Producing static plots</a>
    </li>
    <li>
      <a href="../articles/interactive.html">Producing interactive plots</a>
    </li>
    <li>
      <a href="../articles/clusters.html">Hierarchical clustering</a>
    </li>
    <li>
      <a href="../articles/pipeline.html">Recommended RNA-seq pipeline</a>
    </li>
  </ul>
</li>
<li>
  <a href="../articles/manuscripts.html">
    <span class="fa fa-pencil-square-o"></span>
     
    manuscripts
  </a>
</li>
<li>
  <a href="../news/index.html">
    <span class="fa fa-newspaper-o"></span>
     
    news
  </a>
</li>
<li>
  <a href="../reference/index.html">
    <span class="fa fa-file-code-o"></span>
     
    functions
  </a>
</li>
<li>
  <a href="https://github.com/lindsayrutter/bigPint/">
    <span class="fa fa-github fa-lg"></span>
     
    github
  </a>
</li>
      </ul>
<form class="navbar-form navbar-right hidden-xs hidden-sm" role="search">
        <div class="form-group">
          <input type="search" class="form-control" name="search-input" id="search-input" placeholder="Search..." aria-label="Search for..." autocomplete="off">
</div>
      </form>
      
    </div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Hierarchical clustering</h1>
            
      
      <small class="dont-index">Source: <a href="https://github.com/lindsayrutter/bigPint/blob/master/vignettes/clusters.Rmd"><code>vignettes/clusters.Rmd</code></a></small>
      <div class="hidden name"><code>clusters.Rmd</code></div>

    </div>

    
    
<div id="three-clustering-approaches" class="section level2">
<h2 class="hasAnchor">
<a href="#three-clustering-approaches" class="anchor"></a>Three clustering approaches</h2>
<p>The <code>bigPint</code> package incorporates a function <code><a href="../reference/plotClusters.html">plotClusters()</a></code> for users to conduct hierarchical clustering analyses on their data. This is accomplished through the <code><a href="https://rdrr.io/r/stats/hclust.html">hclust()</a></code> and <code><a href="https://rdrr.io/r/stats/cutree.html">cutree()</a></code> functions in the <a href="https://stat.ethz.ch/R-manual/R-devel/library/stats/html/stats-package.html"><code>stats</code></a> package. By default, the resulting clusters will be plotted as parallel coordinate lines superimposed onto side-by-side boxplots showing the full dataset. This will allow users to quickly view the patterns in the resulting clusters. There are three main approaches to using the <code><a href="../reference/plotClusters.html">plotClusters()</a></code> function:</p>
<ol style="list-style-type: decimal">
<li><p><strong>Approach 1:</strong> The clusters are determined by clustering only on a subset of data (such as significant genes). Only the significant genes are overlaid as parallel coordinate lines.</p></li>
<li><p><strong>Approach 2:</strong> The clusters are determined by clustering the full dataset. Then, only a subset of data (such as significant genes) are overlaid as parallel coordinate lines.</p></li>
<li><p><strong>Approach 3:</strong> The clusters are determined by clustering the full dataset. All genes are overlaid as parallel coordinate lines.</p></li>
</ol>
<p>We will now show examples for each of these three main approaches and discuss a few additional options in the <code><a href="../reference/plotClusters.html">plotClusters()</a></code> function.</p>
<hr>
</div>
<div id="approach-1" class="section level2">
<h2 class="hasAnchor">
<a href="#approach-1" class="anchor"></a>Approach 1</h2>
<p>Below, we read in the soybean iron metabolism dataset and perform a logarithm on it <span class="citation">(Lauter and Graham 2016)</span>. We determine that this dataset contains 5,604 genes. We also determine that this dataset has 113 genes that have FDR &lt; 1e-7 (n = 113). We will consider these our 113 significant genes of interest.</p>
<div class="sourceCode" id="cb1"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">grid</span>)
<span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">matrixStats</span>)
<span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">ggplot2</span>)
<span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">bigPint</span>)
<span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span>(<span class="st">"soybean_ir_sub"</span>)
<span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span>(<span class="st">"soybean_ir_sub_metrics"</span>)
<span class="no">soybean_ir_sub</span>[,-<span class="fl">1</span>] <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span>(<span class="no">soybean_ir_sub</span>[,-<span class="fl">1</span>]+<span class="fl">1</span>)
<span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span>(<span class="no">soybean_ir_sub</span>)</pre></body></html></div>
<pre><code>## [1] 5604</code></pre>
<div class="sourceCode" id="cb3"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/which.html">which</a></span>(<span class="no">soybean_ir_sub_metrics</span><span class="kw">[[</span><span class="st">"N_P"</span>]]$<span class="no">FDR</span> <span class="kw">&lt;</span> <span class="fl">1e-7</span>))</pre></body></html></div>
<pre><code>## [1] 113</code></pre>
<p>We then perform a hierarchical clustering of size four. By setting the <code>clusterAllData</code> parameter to a value of <code>FALSE</code>, our clustering algorithm only considers the 113 significant genes of interest. As a side note, we use the default agglomeration method “ward.D”. We then overlay these 113 genes as parallel coordinate lines across the full dataset represented as side-by-side boxplots.</p>
<div class="sourceCode" id="cb5"><html><body><pre class="r"><span class="no">colList</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"#00A600FF"</span>, <span class="fu"><a href="https://rdrr.io/r/grDevices/palettes.html">rainbow</a></span>(<span class="fl">5</span>)[<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">1</span>,<span class="fl">4</span>,<span class="fl">5</span>)])
<span class="no">ret</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/plotClusters.html">plotClusters</a></span>(<span class="kw">data</span><span class="kw">=</span><span class="no">soybean_ir_sub</span>, <span class="kw">dataMetrics</span> <span class="kw">=</span> <span class="no">soybean_ir_sub_metrics</span>, <span class="kw">nC</span><span class="kw">=</span><span class="fl">4</span>,
  <span class="kw">colList</span> <span class="kw">=</span> <span class="no">colList</span>, <span class="kw">clusterAllData</span> <span class="kw">=</span> <span class="fl">FALSE</span>, <span class="kw">threshVal</span> <span class="kw">=</span> <span class="fl">1e-7</span>, <span class="kw">saveFile</span> <span class="kw">=</span> <span class="fl">FALSE</span>)
<span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span>(<span class="no">ret</span>)</pre></body></html></div>
<pre><code>## [1] "N_P_4"</code></pre>
<div class="sourceCode" id="cb7"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/grid/grid.draw.html">grid.draw</a></span>(<span class="no">ret</span><span class="kw">[[</span><span class="st">"N_P_4"</span>]])</pre></body></html></div>
<p><img src="clusters_files/figure-html/unnamed-chunk-2-1.png" width="700.0000032"></p>
<hr>
</div>
<div id="approach-2" class="section level2">
<h2 class="hasAnchor">
<a href="#approach-2" class="anchor"></a>Approach 2</h2>
<p>We can perform a similar analysis as we did before, only now we will set the <code>clusterAllData</code> parameter to a value of <code>TRUE</code>. This means our four clusters will be created considering <em>all</em> genes in the data (n = 5,604). The clusters will then represent the four main patterns in the full dataset. After that, we will only overlay the 113 significant genes as parallel coordinate lines across the full dataset represented as side-by-side boxplots. Note that Cluster 1 did not contain any of the 113 significant genes.</p>
<div class="sourceCode" id="cb8"><html><body><pre class="r"><span class="no">ret</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/plotClusters.html">plotClusters</a></span>(<span class="kw">data</span><span class="kw">=</span><span class="no">soybean_ir_sub</span>, <span class="kw">dataMetrics</span> <span class="kw">=</span> <span class="no">soybean_ir_sub_metrics</span>, <span class="kw">nC</span><span class="kw">=</span><span class="fl">4</span>,
  <span class="kw">colList</span> <span class="kw">=</span> <span class="no">colList</span>, <span class="kw">clusterAllData</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">threshVal</span> <span class="kw">=</span> <span class="fl">1e-7</span>, <span class="kw">saveFile</span> <span class="kw">=</span> <span class="fl">FALSE</span>)
<span class="fu"><a href="https://rdrr.io/r/grid/grid.draw.html">grid.draw</a></span>(<span class="no">ret</span><span class="kw">[[</span><span class="st">"N_P_4"</span>]])</pre></body></html></div>
<p><img src="clusters_files/figure-html/unnamed-chunk-3-1.png" width="700.0000032"></p>
<hr>
</div>
<div id="approach-3" class="section level2">
<h2 class="hasAnchor">
<a href="#approach-3" class="anchor"></a>Approach 3</h2>
<p>In this last approach, we will perform hierarchical clustering on <em>all</em> 5,604 genes in the data and also overlay <em>all</em> 5,604 genes as parallel coordinate lines. We do not create any subset of genes (such as significant genes) because we leave the <code>dataMetrics</code> object with its default value of <code>NULL</code>.</p>
<div class="sourceCode" id="cb9"><html><body><pre class="r"><span class="no">ret</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/plotClusters.html">plotClusters</a></span>(<span class="kw">data</span><span class="kw">=</span><span class="no">soybean_ir_sub</span>, <span class="kw">nC</span><span class="kw">=</span><span class="fl">4</span>, <span class="kw">colList</span> <span class="kw">=</span> <span class="no">colList</span>,
  <span class="kw">clusterAllData</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">saveFile</span> <span class="kw">=</span> <span class="fl">FALSE</span>)
<span class="fu"><a href="https://rdrr.io/r/grid/grid.draw.html">grid.draw</a></span>(<span class="no">ret</span><span class="kw">[[</span><span class="st">"N_P_4"</span>]])</pre></body></html></div>
<p><img src="clusters_files/figure-html/unnamed-chunk-4-1.png" width="700.0000032"></p>
<p>As a side note, we can use the output from Approach 3 to better understand how Approach 2 worked. Basically, in Approach 2, all 5,604 genes were used in the clustering algorithm to create four clusters. These resulted in the cluster sizes shown in Approach 3: That is, Cluster 1 had 2,334 genes; Cluster 2 had 1,997 genes; Cluster 3 had 1,992 genes; and Cluster 4 had 881 genes. However, at that point, Approach 2 only plotted the 113 significant genes. This means that none of 2,334 genes in Cluster 1 were significant; 44 of the 1,997 genes in Cluster 2 were significant; 33 of the 1,992 genes in Cluster 3 were significant; and 36 of the 881 genes in Cluster 4 were significant.</p>
<hr>
</div>
<div id="standardization" class="section level2">
<h2 class="hasAnchor">
<a href="#standardization" class="anchor"></a>Standardization</h2>
<p>When visualizing hierarchical clustering of genes, it is often recommended to consider the <em>standardized</em> values of read counts <span class="citation">(Chandrasekhar, Thangavel, and Elayaraja 2012)</span>. Below is an example of standardizing gene read counts and plotting their clusters as parallel coordinate plots superimposed onto side-by-side boxplots. The standardization transforms each gene to have a mean of zero and a standard deviation of one across its samples. This example uses the soybean cotyledon dataset, which has three treatment groups (S1, S2, and S3) <span class="citation">(Brown and Hudson 2015)</span>. Only two treatment pairs (S1 and S2; S1 and S3) return significant genes. As a result, our <code>ret</code> object will have these two comparisons.</p>
<div class="sourceCode" id="cb10"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span>(<span class="no">soybean_cn_sub</span>)
<span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span>(<span class="no">soybean_cn_sub_metrics</span>)
<span class="no">soybean_cn_sub_st</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/t.html">t</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/matrix.html">as.matrix</a></span>(<span class="no">soybean_cn_sub</span>[,-<span class="fl">1</span>]), <span class="fl">1</span>,
  <span class="no">scale</span>)))
<span class="no">soybean_cn_sub_st</span>$<span class="no">ID</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/character.html">as.character</a></span>(<span class="no">soybean_cn_sub</span>$<span class="no">ID</span>)
<span class="no">soybean_cn_sub_st</span> <span class="kw">&lt;-</span> <span class="no">soybean_cn_sub_st</span>[,<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span>(<span class="no">soybean_cn_sub_st</span>),
  <span class="fl">1</span>:<span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span>(<span class="no">soybean_cn_sub_st</span>)-<span class="fl">1</span>)]
<span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span>(<span class="no">soybean_cn_sub_st</span>) <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span>(<span class="no">soybean_cn_sub</span>)
<span class="no">nID</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/which.html">which</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/is.finite.html">is.nan</a></span>(<span class="no">soybean_cn_sub_st</span>[,<span class="fl">2</span>]))
<span class="no">soybean_cn_sub_st</span>[<span class="no">nID</span>,<span class="fl">2</span>:<span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span>(<span class="no">soybean_cn_sub_st</span>)] <span class="kw">&lt;-</span> <span class="fl">0</span>
<span class="no">ret</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/plotClusters.html">plotClusters</a></span>(<span class="kw">data</span><span class="kw">=</span><span class="no">soybean_cn_sub_st</span>, <span class="kw">dataMetrics</span> <span class="kw">=</span> <span class="no">soybean_cn_sub_metrics</span>,
  <span class="kw">nC</span><span class="kw">=</span><span class="fl">4</span>, <span class="kw">colList</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"#00A600FF"</span>, <span class="st">"#CC00FFFF"</span>, <span class="st">"red"</span>, <span class="st">"darkorange"</span>), <span class="kw">lineSize</span> <span class="kw">=</span> <span class="fl">0.5</span>,
  <span class="kw">lineAlpha</span> <span class="kw">=</span> <span class="fl">1</span>, <span class="kw">clusterAllData</span> <span class="kw">=</span> <span class="fl">FALSE</span>, <span class="kw">aggMethod</span> <span class="kw">=</span> <span class="st">"average"</span>,
  <span class="kw">yAxisLabel</span> <span class="kw">=</span> <span class="st">"Standardized read count"</span>, <span class="kw">saveFile</span> <span class="kw">=</span> <span class="fl">FALSE</span>)</pre></body></html></div>
<pre><code>## [1] "S2_S3: There were no significant genes"</code></pre>
<div class="sourceCode" id="cb12"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span>(<span class="no">ret</span>)</pre></body></html></div>
<pre><code>## [1] "S1_S2_4" "S1_S3_4" "S2_S3_4"</code></pre>
<div class="sourceCode" id="cb14"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/grid/grid.draw.html">grid.draw</a></span>(<span class="no">ret</span><span class="kw">[[</span><span class="st">"S1_S2_4"</span>]])</pre></body></html></div>
<p><img src="clusters_files/figure-html/unnamed-chunk-5-1.png" width="700.0000032"></p>
<div class="sourceCode" id="cb15"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/grid/grid.draw.html">grid.draw</a></span>(<span class="no">ret</span><span class="kw">[[</span><span class="st">"S1_S3_4"</span>]])</pre></body></html></div>
<p><img src="clusters_files/figure-html/unnamed-chunk-6-1.png" width="700.0000032"></p>
<hr>
</div>
<div id="verbose-option" class="section level2">
<h2 class="hasAnchor">
<a href="#verbose-option" class="anchor"></a>Verbose option</h2>
<p>In some cases, users may wish to use the <code><a href="../reference/plotClusters.html">plotClusters()</a></code> function to create clusters and then save these clusters to use for other purposes later, such as overlaying them onto scatterplot matrices, litre plots, and volcano plots. The gene IDs of the parallel coordinate lines in each cluster can be saved as .rds files for this purpose by setting the <code>verbose</code> option to a value of <code>TRUE</code>. Below is an example of this:</p>
<div class="sourceCode" id="cb16"><html><body><pre class="r"><span class="fu"><a href="../reference/plotClusters.html">plotClusters</a></span>(<span class="kw">data</span><span class="kw">=</span><span class="no">soybean_cn_sub_st</span>, <span class="kw">dataMetrics</span> <span class="kw">=</span> <span class="no">soybean_cn_sub_metrics</span>, <span class="kw">nC</span><span class="kw">=</span><span class="fl">4</span>,
  <span class="kw">colList</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"#00A600FF"</span>, <span class="st">"#CC00FFFF"</span>, <span class="st">"red"</span>, <span class="st">"darkorange"</span>), <span class="kw">lineSize</span> <span class="kw">=</span> <span class="fl">0.5</span>,
  <span class="kw">lineAlpha</span> <span class="kw">=</span> <span class="fl">1</span>, <span class="kw">clusterAllData</span> <span class="kw">=</span> <span class="fl">FALSE</span>, <span class="kw">aggMethod</span> <span class="kw">=</span> <span class="st">"average"</span>,
  <span class="kw">yAxisLabel</span> <span class="kw">=</span> <span class="st">"Standardized read count"</span>, <span class="kw">verbose</span> <span class="kw">=</span> <span class="fl">TRUE</span>)</pre></body></html></div>
<p>Running the command above will save numerous files into the <code>outDir</code> location. The default location is a temporary directory. You can find the exact pathway of this temporary directory by simply typing <code><a href="https://rdrr.io/r/base/tempfile.html">tempdir()</a></code> into your R console. This temporary directory and the files within it remain the same until you close your R session; at that point, a new temporary directory will be created. After running the above command, you should find the following files in your temporary directory:</p>
<ul>
<li><p>S1_S2_4_1.rds (10 gene IDs in Cluster 1 in S1 versus S2 comparison)</p></li>
<li><p>S1_S2_4_1.jpg (Individual plot of Cluster 1 in S1 versus S2 comparison)</p></li>
<li><p>S1_S2_4_2.rds (3 gene IDs in Cluster 1 in S1 versus S2 comparison)</p></li>
<li><p>S1_S2_4_2.jpg (Individual plot of Cluster 2 in S1 versus S2 comparison)</p></li>
<li><p>S1_S2_4_3.rds (2 gene IDs in Cluster 1 in S1 versus S2 comparison)</p></li>
<li><p>S1_S2_4_3.jpg (Individual plot of Cluster 3 in S1 versus S2 comparison)</p></li>
<li><p>S1_S2_4_4.rds (1 gene IDs in Cluster 1 in S1 versus S2 comparison)</p></li>
<li><p>S1_S2_4_4.jpg (Individual plot of Cluster 4 in S1 versus S2 comparison)</p></li>
<li><p>S1_S2_4.jpg (Plot of all four clusters in S1 versus S2 comparison)</p></li>
<li><p>S1_S3_4_1.rds (19 gene IDs in Cluster 1 in S1 versus S3 comparison)</p></li>
<li><p>S1_S3_4_1.jpg (Individual plot of Cluster 1 in S1 versus S3 comparison)</p></li>
<li><p>S1_S3_4_2.rds (7 gene IDs in Cluster 2 in S1 versus S3 comparison)</p></li>
<li><p>S1_S3_4_2.jpg (Individual plot of Cluster 2 in S1 versus S3 comparison)</p></li>
<li><p>S1_S3_4_3.rds (2 gene IDs in Cluster 3 in S1 versus S3 comparison)</p></li>
<li><p>S1_S3_4_3.jpg (Individual plot of Cluster 3 in S1 versus S3 comparison)</p></li>
<li><p>S1_S3_4_4.rds (2 gene IDs in Cluster 4 in S1 versus S3 comparison)</p></li>
<li><p>S1_S3_4_4.jpg (Individual plot of Cluster 4 in S1 versus S3 comparison)</p></li>
<li><p>S1_S3_4.jpg (Plot of all four clusters in S1 versus S3 comparison)</p></li>
</ul>
<p>At this point, we can use any of the .rds files to examine the genes represented in the clustered parallel coordinate plots. For instance, we can read in the 19 Cluster 1 genes in the S1 versus S3 comparison as follows:</p>
<div class="sourceCode" id="cb17"><html><body><pre class="r"><span class="no">S1S3Cluster1</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/readRDS.html">readRDS</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/tempfile.html">tempdir</a></span>(), <span class="st">"/S1_S3_4_1.rds"</span>))</pre></body></html></div>
<p>And check its contents contain the 19 gene IDs.</p>
<div class="sourceCode" id="cb18"><html><body><pre class="r"><span class="no">S1S3Cluster1</span></pre></body></html></div>
<pre><code>##  [1] "Glyma18g00690.1" "Glyma08g44110.1" "Glyma01g26570.1" "Glyma07g09700.1"
##  [5] "Glyma02g40610.1" "Glyma17g17970.1" "Glyma19g26250.1" "Glyma10g34630.1"
##  [9] "Glyma14g14220.1" "Glyma19g26710.1" "Glyma03g29150.1" "Glyma08g19245.1"
## [13] "Glyma07g01730.2" "Glyma18g25845.1" "Glyma08g22380.1" "Glyma20g30460.1"
## [17] "Glyma12g10960.1" "Glyma16g08810.1" "Glyma18g42630.2"</code></pre>
<p>Then, we can overlay these 19 genes from Cluster 1 in the S1 versus S3 comparison as points onto the scatterplot matrix. This step can give us another perspective of these 19 genes. We may wish to use the same color (green) that we did in the parallel coordinate plots above and add an informative plot title.</p>
<div class="sourceCode" id="cb20"><html><body><pre class="r"><span class="no">ret</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/plotSM.html">plotSM</a></span>(<span class="kw">data</span> <span class="kw">=</span> <span class="no">soybean_cn_sub_st</span>, <span class="kw">geneList</span> <span class="kw">=</span> <span class="no">S1S3Cluster1</span>,
  <span class="kw">pointColor</span> <span class="kw">=</span> <span class="st">"#00A600FF"</span>, <span class="kw">saveFile</span> <span class="kw">=</span> <span class="fl">FALSE</span>)
<span class="no">ret</span><span class="kw">[[</span><span class="st">"S1_S3"</span>]] + <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span>(<span class="st">"Cluster 1 Genes (n=19)"</span>)</pre></body></html></div>
<p><img src="clusters_files/figure-html/unnamed-chunk-14-1.png" width="700.0000032"></p>
<hr>
</div>
<div id="pre-determined-clusters" class="section level2">
<h2 class="hasAnchor">
<a href="#pre-determined-clusters" class="anchor"></a>Pre-determined clusters</h2>
<p>Some users may perform clustering using other software and may wish to simply overlay those clusters as parallel coordinate plots using the <code>bigPint</code> package. This can be achieved in the <code><a href="../reference/plotClusters.html">plotClusters()</a></code> function using the <code>geneLists</code> variable. As an example, let us read in three clusters that each contain a character array of gene IDs. Hypothetically, these three clusters may have been created in another software package and we simply now wish to plot them out using the <code>bigPint</code> graphics. We see that the first cluster contains 7 gene IDs and the last two clusters each contain 2 gene IDs.</p>
<div class="sourceCode" id="cb21"><html><body><pre class="r"><span class="no">S1S3Cluster2</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/readRDS.html">readRDS</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/tempfile.html">tempdir</a></span>(), <span class="st">"/S1_S3_4_2.rds"</span>))
<span class="no">S1S3Cluster3</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/readRDS.html">readRDS</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/tempfile.html">tempdir</a></span>(), <span class="st">"/S1_S3_4_3.rds"</span>))
<span class="no">S1S3Cluster4</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/readRDS.html">readRDS</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/tempfile.html">tempdir</a></span>(), <span class="st">"/S1_S3_4_4.rds"</span>))</pre></body></html></div>
<div class="sourceCode" id="cb22"><html><body><pre class="r"><span class="no">S1S3Cluster2</span></pre></body></html></div>
<pre><code>## [1] "Glyma06g12670.1" "Glyma12g32460.1" "Glyma17g09850.1" "Glyma18g52920.1"
## [5] "Glyma01g24710.1" "Glyma04g39880.1" "Glyma05g27450.2"</code></pre>
<div class="sourceCode" id="cb24"><html><body><pre class="r"><span class="no">S1S3Cluster3</span></pre></body></html></div>
<pre><code>## [1] "Glyma04g37510.1" "Glyma03g19880.1"</code></pre>
<div class="sourceCode" id="cb26"><html><body><pre class="r"><span class="no">S1S3Cluster4</span></pre></body></html></div>
<pre><code>## [1] "Glyma08g11570.1" "Glyma08g19290.1"</code></pre>
<p>We can now plot these three clusters directly as parallel coordinate lines superimposed on side-by-side boxplots as follows:</p>
<div class="sourceCode" id="cb28"><html><body><pre class="r"><span class="no">ret</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/plotClusters.html">plotClusters</a></span>(<span class="kw">data</span><span class="kw">=</span><span class="no">soybean_cn_sub_st</span>, <span class="kw">geneLists</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span>(<span class="no">S1S3Cluster2</span>,
  <span class="no">S1S3Cluster3</span>, <span class="no">S1S3Cluster4</span>), <span class="kw">lineAlpha</span> <span class="kw">=</span> <span class="fl">1</span>, <span class="kw">lineSize</span> <span class="kw">=</span> <span class="fl">0.5</span>)
<span class="fu"><a href="https://rdrr.io/r/grid/grid.draw.html">grid.draw</a></span>(<span class="no">ret</span><span class="kw">[[</span><span class="st">"S1_S3_3"</span>]])</pre></body></html></div>
<p><img src="clusters_files/figure-html/unnamed-chunk-17-1.png" width="700.0000032"></p>
<hr>
</div>
<div id="three-treatment-groups" class="section level2">
<h2 class="hasAnchor">
<a href="#three-treatment-groups" class="anchor"></a>Three treatment groups</h2>
<p>We note that, when there are more than two treatment groups, users can decide whether to plot clustering results onto just the pair of treatment groups that were used in the clustering analysis or onto all treatment groups in the data nonetheless. This can be tailored using the <code>showPairs</code> parameter. When set to the default value of <code>TRUE</code>, only the treatment pair that was used to generate the clustering results is shown. Below are four examples illustrating this concept using the standardized cotyledon soybean dataset we read into the session earlier (<code>soybean_cn_sub_st</code>).</p>
<p>In the first example, we set <code>clusterAllData</code> to <code>TRUE</code> and <code>showPairs</code> to <code>FALSE</code>. Since we set <code>clusterAllData</code> to <code>TRUE</code>, clustering analysis is performed on all 7332 genes in the data. After each of the 7332 genes is assigned to one of the clusters, only the 284 significant genes are plotted as parallel coordinate lines. Note that <code>retTF</code> below contains <code>S1_S2</code>, <code>S1_S3</code>, and <code>S2_S3</code> comparisons but that we only show <code>S1_S2</code> below for simplicity. Since we set <code>showPairs</code> to <code>FALSE</code>, we do not restrict the output for each pairwise comparison to only show the treatment pair in question. Hence, below we see the S1, S2, and S3 output.</p>
<div class="sourceCode" id="cb29"><html><body><pre class="r"><span class="no">retTF</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/plotClusters.html">plotClusters</a></span>(<span class="no">soybean_cn_sub_st</span>, <span class="no">soybean_cn_sub_metrics</span>, <span class="kw">threshVar</span><span class="kw">=</span><span class="st">"PValue"</span>,
<span class="kw">threshVal</span> <span class="kw">=</span> <span class="fl">0.05</span>, <span class="kw">nC</span> <span class="kw">=</span> <span class="fl">4</span>, <span class="kw">lineSize</span> <span class="kw">=</span> <span class="fl">0.5</span>, <span class="kw">verbose</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">clusterAllData</span> <span class="kw">=</span> <span class="fl">TRUE</span>,
<span class="kw">showPairs</span> <span class="kw">=</span> <span class="fl">FALSE</span>, <span class="kw">vxAxis</span> <span class="kw">=</span> <span class="fl">TRUE</span>)

<span class="fu"><a href="https://rdrr.io/r/grid/grid.draw.html">grid.draw</a></span>(<span class="no">retTF</span><span class="kw">[[</span><span class="st">"S1_S2_4"</span>]])</pre></body></html></div>
<p><img src="clusters_files/figure-html/unnamed-chunk-18-1.png" width="700.0000032"></p>
<p>In the second example, we still set <code>clusterAllData</code> to <code>TRUE</code> but we now also set <code>showPairs</code> to <code>TRUE</code>. Since we set <code>clusterAllData</code> to <code>TRUE</code>, clustering analysis is performed on all 7332 genes in the data. After each of the 7332 genes is assigned to one of the clusters, only the 284 significant genes are plotted as parallel coordinate lines. Note that <code>retTT</code> below contains <code>S1_S2</code>, <code>S1_S3</code>, and <code>S2_S3</code> comparisons but that we only show <code>S1_S2</code> below for simplicity. Since we set <code>showPairs</code> to <code>TRUE</code>, we only plot the treatment pair in question for each pairwise comparison. Hence, below we only see the S1 and S2 output.</p>
<div class="sourceCode" id="cb30"><html><body><pre class="r"><span class="no">retTT</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/plotClusters.html">plotClusters</a></span>(<span class="no">soybean_cn_sub_st</span>, <span class="no">soybean_cn_sub_metrics</span>, <span class="kw">threshVar</span><span class="kw">=</span><span class="st">"PValue"</span>,
<span class="kw">threshVal</span> <span class="kw">=</span> <span class="fl">0.05</span>, <span class="kw">nC</span> <span class="kw">=</span> <span class="fl">4</span>, <span class="kw">lineSize</span> <span class="kw">=</span> <span class="fl">0.5</span>, <span class="kw">verbose</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">clusterAllData</span> <span class="kw">=</span> <span class="fl">TRUE</span>,
<span class="kw">showPairs</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">vxAxis</span> <span class="kw">=</span> <span class="fl">TRUE</span>)

<span class="fu"><a href="https://rdrr.io/r/grid/grid.draw.html">grid.draw</a></span>(<span class="no">retTT</span><span class="kw">[[</span><span class="st">"S1_S2_4"</span>]])</pre></body></html></div>
<p><img src="clusters_files/figure-html/unnamed-chunk-19-1.png" width="700.0000032"></p>
<p>In the third example, we set <code>clusterAllData</code> to <code>FALSE</code> and <code>showPairs</code> to <code>FALSE</code>. Since we set <code>clusterAllData</code> to <code>FALSE</code>, clustering analysis is performed on only the 284 significant genes, which are then plotted as parallel coordinate lines. Note that <code>retFF</code> below contains <code>S1_S2</code>, <code>S1_S3</code>, and <code>S2_S3</code> comparisons but that we only show <code>S1_S2</code> below for simplicity. Since we set <code>showPairs</code> to <code>FALSE</code>, we do not restrict the output for each pairwise comparison to only show the treatment pair in question. Hence, below we see the S1, S2, and S3 output.</p>
<div class="sourceCode" id="cb31"><html><body><pre class="r"><span class="no">retFF</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/plotClusters.html">plotClusters</a></span>(<span class="no">soybean_cn_sub_st</span>, <span class="no">soybean_cn_sub_metrics</span>, <span class="kw">threshVar</span><span class="kw">=</span><span class="st">"PValue"</span>,
<span class="kw">threshVal</span> <span class="kw">=</span> <span class="fl">0.05</span>, <span class="kw">nC</span> <span class="kw">=</span> <span class="fl">4</span>, <span class="kw">lineSize</span> <span class="kw">=</span> <span class="fl">0.5</span>, <span class="kw">verbose</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">clusterAllData</span> <span class="kw">=</span> <span class="fl">FALSE</span>,
<span class="kw">showPairs</span> <span class="kw">=</span> <span class="fl">FALSE</span>, <span class="kw">vxAxis</span> <span class="kw">=</span> <span class="fl">TRUE</span>)

<span class="fu"><a href="https://rdrr.io/r/grid/grid.draw.html">grid.draw</a></span>(<span class="no">retFF</span><span class="kw">[[</span><span class="st">"S1_S2_4"</span>]])</pre></body></html></div>
<p><img src="clusters_files/figure-html/unnamed-chunk-20-1.png" width="700.0000032"></p>
<p>In the fourth example, we still set <code>clusterAllData</code> to <code>FALSE</code> but we now set <code>showPairs</code> to <code>TRUE</code>. Since we set <code>clusterAllData</code> to <code>FALSE</code>, clustering analysis is performed on only the 284 significant genes, which are then plotted as parallel coordinate lines. Note that <code>retFT</code> below contains <code>S1_S2</code>, <code>S1_S3</code>, and <code>S2_S3</code> comparisons but that we only show <code>S1_S2</code> below for simplicity. Since we set <code>showPairs</code> to <code>TRUE</code>, we only plot the treatment pair in question for each pairwise comparison. Hence, below we only see the S1 and S2 output.</p>
<div class="sourceCode" id="cb32"><html><body><pre class="r"><span class="no">retFT</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/plotClusters.html">plotClusters</a></span>(<span class="no">soybean_cn_sub_st</span>, <span class="no">soybean_cn_sub_metrics</span>, <span class="kw">threshVar</span><span class="kw">=</span><span class="st">"PValue"</span>, <span class="kw">threshVal</span> <span class="kw">=</span> <span class="fl">0.05</span>, <span class="kw">nC</span> <span class="kw">=</span> <span class="fl">4</span>, <span class="kw">lineSize</span> <span class="kw">=</span> <span class="fl">0.5</span>, <span class="kw">verbose</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">clusterAllData</span> <span class="kw">=</span> <span class="fl">FALSE</span>,
<span class="kw">showPairs</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">vxAxis</span> <span class="kw">=</span> <span class="fl">TRUE</span>)

<span class="fu"><a href="https://rdrr.io/r/grid/grid.draw.html">grid.draw</a></span>(<span class="no">retFT</span><span class="kw">[[</span><span class="st">"S1_S2_4"</span>]])</pre></body></html></div>
<p><img src="clusters_files/figure-html/unnamed-chunk-21-1.png" width="700.0000032"></p>
<hr>
</div>
<div id="summarizedexperiment-version" class="section level2">
<h2 class="hasAnchor">
<a href="#summarizedexperiment-version" class="anchor"></a>SummarizedExperiment version</h2>
<p>Below are the corresponding code blocks from everything above that now use the <code>SummarizedExperiment</code> object (<code>dataSE</code>) instead of the <code>data</code> and <code>dataMetrics</code> objects.</p>
<div id="approach-1-1" class="section level3">
<h3 class="hasAnchor">
<a href="#approach-1-1" class="anchor"></a>Approach 1</h3>
<div class="sourceCode" id="cb33"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">grid</span>)
<span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">matrixStats</span>)
<span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">ggplot2</span>)
<span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">bigPint</span>)
<span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">DelayedArray</span>)
<span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">SummarizedExperiment</span>)
<span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span>(<span class="st">"se_soybean_ir_sub"</span>)
<span class="fu"><a href="https://rdrr.io/pkg/SummarizedExperiment/man/SummarizedExperiment-class.html">assay</a></span>(<span class="no">se_soybean_ir_sub</span>) <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span>(<span class="fu"><a href="https://rdrr.io/pkg/SummarizedExperiment/man/SummarizedExperiment-class.html">assay</a></span>(<span class="no">se_soybean_ir_sub</span>))+<span class="fl">1</span>)
<span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span>(<span class="no">se_soybean_ir_sub</span>)</pre></body></html></div>
<div class="sourceCode" id="cb34"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/which.html">which</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span>(<span class="fu"><a href="https://rdrr.io/pkg/SummarizedExperiment/man/SummarizedExperiment-class.html">rowData</a></span>(<span class="no">se_soybean_ir_sub</span>))$<span class="no">N_P.FDR</span> <span class="kw">&lt;</span> <span class="fl">1e-7</span>))</pre></body></html></div>
<div class="sourceCode" id="cb35"><html><body><pre class="r"><span class="no">colList</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"#00A600FF"</span>, <span class="fu"><a href="https://rdrr.io/r/grDevices/palettes.html">rainbow</a></span>(<span class="fl">5</span>)[<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">1</span>,<span class="fl">4</span>,<span class="fl">5</span>)])
<span class="no">ret</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/plotClusters.html">plotClusters</a></span>(<span class="kw">dataSE</span><span class="kw">=</span><span class="no">se_soybean_ir_sub</span>, <span class="kw">nC</span><span class="kw">=</span><span class="fl">4</span>, <span class="kw">colList</span> <span class="kw">=</span> <span class="no">colList</span>,
  <span class="kw">clusterAllData</span> <span class="kw">=</span> <span class="fl">FALSE</span>, <span class="kw">threshVal</span> <span class="kw">=</span> <span class="fl">1e-7</span>, <span class="kw">saveFile</span> <span class="kw">=</span> <span class="fl">FALSE</span>)
<span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span>(<span class="no">ret</span>)
<span class="fu"><a href="https://rdrr.io/r/grid/grid.draw.html">grid.draw</a></span>(<span class="no">ret</span><span class="kw">[[</span><span class="st">"N_P_4"</span>]])</pre></body></html></div>
<hr>
</div>
<div id="approach-2-1" class="section level3">
<h3 class="hasAnchor">
<a href="#approach-2-1" class="anchor"></a>Approach 2</h3>
<div class="sourceCode" id="cb36"><html><body><pre class="r"><span class="no">ret</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/plotClusters.html">plotClusters</a></span>(<span class="kw">dataSE</span><span class="kw">=</span><span class="no">se_soybean_ir_sub</span>, <span class="kw">nC</span><span class="kw">=</span><span class="fl">4</span>, <span class="kw">colList</span> <span class="kw">=</span> <span class="no">colList</span>,
  <span class="kw">clusterAllData</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">threshVal</span> <span class="kw">=</span> <span class="fl">1e-7</span>, <span class="kw">saveFile</span> <span class="kw">=</span> <span class="fl">FALSE</span>)
<span class="fu"><a href="https://rdrr.io/r/grid/grid.draw.html">grid.draw</a></span>(<span class="no">ret</span><span class="kw">[[</span><span class="st">"N_P_4"</span>]])</pre></body></html></div>
<hr>
</div>
<div id="approach-3-1" class="section level3">
<h3 class="hasAnchor">
<a href="#approach-3-1" class="anchor"></a>Approach 3</h3>
<div class="sourceCode" id="cb37"><html><body><pre class="r"><span class="no">se_soybean_ir_sub_nm</span> <span class="kw">&lt;-</span> <span class="no">se_soybean_ir_sub</span>
<span class="fu"><a href="https://rdrr.io/pkg/SummarizedExperiment/man/SummarizedExperiment-class.html">rowData</a></span>(<span class="no">se_soybean_ir_sub_nm</span>) <span class="kw">&lt;-</span> <span class="kw">NULL</span>
<span class="no">ret</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/plotClusters.html">plotClusters</a></span>(<span class="kw">dataSE</span><span class="kw">=</span><span class="no">se_soybean_ir_sub_nm</span>, <span class="kw">nC</span><span class="kw">=</span><span class="fl">4</span>, <span class="kw">colList</span> <span class="kw">=</span> <span class="no">colList</span>,
  <span class="kw">clusterAllData</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">saveFile</span> <span class="kw">=</span> <span class="fl">FALSE</span>)
<span class="fu"><a href="https://rdrr.io/r/grid/grid.draw.html">grid.draw</a></span>(<span class="no">ret</span><span class="kw">[[</span><span class="st">"N_P_4"</span>]])</pre></body></html></div>
<hr>
</div>
<div id="standardization-1" class="section level3">
<h3 class="hasAnchor">
<a href="#standardization-1" class="anchor"></a>Standardization</h3>
<div class="sourceCode" id="cb38"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span>(<span class="no">se_soybean_cn_sub</span>)

<span class="no">se_soybean_cn_sub_st</span> <span class="kw">=</span> <span class="no">se_soybean_cn_sub</span>
<span class="fu"><a href="https://rdrr.io/pkg/SummarizedExperiment/man/SummarizedExperiment-class.html">assay</a></span>(<span class="no">se_soybean_cn_sub_st</span>) <span class="kw">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span>(<span class="fu"><a href="https://rdrr.io/pkg/DelayedArray/man/DelayedMatrix-utils.html">t</a></span>(<span class="fu"><a href="https://rdrr.io/pkg/DelayedArray/man/DelayedArray-utils.html">apply</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/matrix.html">as.matrix</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span>(
  <span class="fu"><a href="https://rdrr.io/pkg/SummarizedExperiment/man/SummarizedExperiment-class.html">assay</a></span>(<span class="no">se_soybean_cn_sub</span>))), <span class="fl">1</span>, <span class="no">scale</span>)))
<span class="no">nID</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/which.html">which</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/is.finite.html">is.nan</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span>(<span class="fu"><a href="https://rdrr.io/pkg/SummarizedExperiment/man/SummarizedExperiment-class.html">assay</a></span>(<span class="no">se_soybean_cn_sub_st</span>))[,<span class="fl">1</span>]))
<span class="fu"><a href="https://rdrr.io/pkg/SummarizedExperiment/man/SummarizedExperiment-class.html">assay</a></span>(<span class="no">se_soybean_cn_sub_st</span>)[<span class="no">nID</span>,] <span class="kw">&lt;-</span> <span class="fl">0</span></pre></body></html></div>
<div class="sourceCode" id="cb39"><html><body><pre class="r"><span class="no">ret</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/plotClusters.html">plotClusters</a></span>(<span class="kw">dataSE</span><span class="kw">=</span><span class="no">se_soybean_cn_sub_st</span>, <span class="kw">nC</span><span class="kw">=</span><span class="fl">4</span>,
  <span class="kw">colList</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"#00A600FF"</span>, <span class="st">"#CC00FFFF"</span>, <span class="st">"red"</span>, <span class="st">"darkorange"</span>), <span class="kw">lineSize</span> <span class="kw">=</span> <span class="fl">0.5</span>,
  <span class="kw">lineAlpha</span> <span class="kw">=</span> <span class="fl">1</span>, <span class="kw">clusterAllData</span> <span class="kw">=</span> <span class="fl">FALSE</span>, <span class="kw">aggMethod</span> <span class="kw">=</span> <span class="st">"average"</span>,
  <span class="kw">yAxisLabel</span> <span class="kw">=</span> <span class="st">"Standardized read count"</span>, <span class="kw">saveFile</span> <span class="kw">=</span> <span class="fl">FALSE</span>)

<span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span>(<span class="no">ret</span>)
<span class="fu"><a href="https://rdrr.io/r/grid/grid.draw.html">grid.draw</a></span>(<span class="no">ret</span><span class="kw">[[</span><span class="st">"S1_S2_4"</span>]])
<span class="fu"><a href="https://rdrr.io/r/grid/grid.draw.html">grid.draw</a></span>(<span class="no">ret</span><span class="kw">[[</span><span class="st">"S1_S3_4"</span>]])</pre></body></html></div>
<hr>
</div>
<div id="verbose-option-1" class="section level3">
<h3 class="hasAnchor">
<a href="#verbose-option-1" class="anchor"></a>Verbose option</h3>
<div class="sourceCode" id="cb40"><html><body><pre class="r"><span class="fu"><a href="../reference/plotClusters.html">plotClusters</a></span>(<span class="kw">dataSE</span><span class="kw">=</span><span class="no">se_soybean_cn_sub_st</span>, <span class="kw">nC</span><span class="kw">=</span><span class="fl">4</span>,
  <span class="kw">colList</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"#00A600FF"</span>, <span class="st">"#CC00FFFF"</span>, <span class="st">"red"</span>, <span class="st">"darkorange"</span>), <span class="kw">lineSize</span> <span class="kw">=</span> <span class="fl">0.5</span>,
  <span class="kw">lineAlpha</span> <span class="kw">=</span> <span class="fl">1</span>, <span class="kw">clusterAllData</span> <span class="kw">=</span> <span class="fl">FALSE</span>, <span class="kw">aggMethod</span> <span class="kw">=</span> <span class="st">"average"</span>,
  <span class="kw">yAxisLabel</span> <span class="kw">=</span> <span class="st">"Standardized read count"</span>, <span class="kw">verbose</span> <span class="kw">=</span> <span class="fl">TRUE</span>)</pre></body></html></div>
<div class="sourceCode" id="cb41"><html><body><pre class="r"><span class="no">S1S3Cluster1</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/readRDS.html">readRDS</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/tempfile.html">tempdir</a></span>(), <span class="st">"/S1_S3_4_1.rds"</span>))
<span class="no">S1S3Cluster1</span></pre></body></html></div>
<div class="sourceCode" id="cb42"><html><body><pre class="r"><span class="no">ret</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/plotSM.html">plotSM</a></span>(<span class="kw">dataSE</span> <span class="kw">=</span> <span class="no">se_soybean_cn_sub_st</span>, <span class="kw">geneList</span> <span class="kw">=</span> <span class="no">S1S3Cluster1</span>,
  <span class="kw">pointColor</span> <span class="kw">=</span> <span class="st">"#00A600FF"</span>, <span class="kw">saveFile</span> <span class="kw">=</span> <span class="fl">FALSE</span>)
<span class="no">ret</span><span class="kw">[[</span><span class="st">"S1_S3"</span>]] + <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span>(<span class="st">"Cluster 1 Genes (n=19)"</span>)</pre></body></html></div>
<hr>
</div>
<div id="pre-determined-clusters-1" class="section level3">
<h3 class="hasAnchor">
<a href="#pre-determined-clusters-1" class="anchor"></a>Pre-determined clusters</h3>
<div class="sourceCode" id="cb43"><html><body><pre class="r"><span class="no">S1S3Cluster2</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/readRDS.html">readRDS</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/tempfile.html">tempdir</a></span>(), <span class="st">"/S1_S3_4_2.rds"</span>))
<span class="no">S1S3Cluster3</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/readRDS.html">readRDS</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/tempfile.html">tempdir</a></span>(), <span class="st">"/S1_S3_4_3.rds"</span>))
<span class="no">S1S3Cluster4</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/readRDS.html">readRDS</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/tempfile.html">tempdir</a></span>(), <span class="st">"/S1_S3_4_4.rds"</span>))</pre></body></html></div>
<div class="sourceCode" id="cb44"><html><body><pre class="r"><span class="no">S1S3Cluster2</span>
<span class="no">S1S3Cluster3</span>
<span class="no">S1S3Cluster4</span></pre></body></html></div>
<div class="sourceCode" id="cb45"><html><body><pre class="r"><span class="no">ret</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/plotClusters.html">plotClusters</a></span>(<span class="kw">dataSE</span><span class="kw">=</span><span class="no">se_soybean_cn_sub_st</span>, <span class="kw">geneLists</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span>(<span class="no">S1S3Cluster2</span>,
  <span class="no">S1S3Cluster3</span>, <span class="no">S1S3Cluster4</span>), <span class="kw">lineAlpha</span> <span class="kw">=</span> <span class="fl">1</span>, <span class="kw">lineSize</span> <span class="kw">=</span> <span class="fl">0.5</span>)
<span class="fu"><a href="https://rdrr.io/r/grid/grid.draw.html">grid.draw</a></span>(<span class="no">ret</span><span class="kw">[[</span><span class="st">"S1_S3_3"</span>]])</pre></body></html></div>
<hr>
</div>
<div id="three-treatment-groups-1" class="section level3">
<h3 class="hasAnchor">
<a href="#three-treatment-groups-1" class="anchor"></a>Three treatment groups</h3>
<div class="sourceCode" id="cb46"><html><body><pre class="r"><span class="no">retTF</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/plotClusters.html">plotClusters</a></span>(<span class="kw">dataSE</span><span class="kw">=</span><span class="no">se_soybean_cn_sub_st</span>, <span class="kw">threshVar</span><span class="kw">=</span><span class="st">"PValue"</span> ,<span class="kw">threshVal</span> <span class="kw">=</span> <span class="fl">0.05</span>, <span class="kw">nC</span> <span class="kw">=</span> <span class="fl">4</span>, <span class="kw">lineSize</span> <span class="kw">=</span> <span class="fl">0.5</span>, <span class="kw">verbose</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">clusterAllData</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">showPairs</span> <span class="kw">=</span> <span class="fl">FALSE</span>, <span class="kw">vxAxis</span> <span class="kw">=</span> <span class="fl">TRUE</span>)
<span class="fu"><a href="https://rdrr.io/r/grid/grid.draw.html">grid.draw</a></span>(<span class="no">retTF</span><span class="kw">[[</span><span class="st">"S1_S2_4"</span>]])</pre></body></html></div>
<div class="sourceCode" id="cb47"><html><body><pre class="r"><span class="no">retTT</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/plotClusters.html">plotClusters</a></span>(<span class="kw">dataSE</span><span class="kw">=</span><span class="no">se_soybean_cn_sub_st</span>, <span class="kw">threshVar</span><span class="kw">=</span><span class="st">"PValue"</span> ,<span class="kw">threshVal</span> <span class="kw">=</span> <span class="fl">0.05</span>, <span class="kw">nC</span> <span class="kw">=</span> <span class="fl">4</span>, <span class="kw">lineSize</span> <span class="kw">=</span> <span class="fl">0.5</span>, <span class="kw">verbose</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">clusterAllData</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">showPairs</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">vxAxis</span> <span class="kw">=</span> <span class="fl">TRUE</span>)
<span class="fu"><a href="https://rdrr.io/r/grid/grid.draw.html">grid.draw</a></span>(<span class="no">retTT</span><span class="kw">[[</span><span class="st">"S1_S2_4"</span>]])</pre></body></html></div>
<div class="sourceCode" id="cb48"><html><body><pre class="r"><span class="no">retFF</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/plotClusters.html">plotClusters</a></span>(<span class="kw">dataSE</span><span class="kw">=</span><span class="no">se_soybean_cn_sub_st</span>, <span class="kw">threshVar</span><span class="kw">=</span><span class="st">"PValue"</span> ,<span class="kw">threshVal</span> <span class="kw">=</span> <span class="fl">0.05</span>, <span class="kw">nC</span> <span class="kw">=</span> <span class="fl">4</span>, <span class="kw">lineSize</span> <span class="kw">=</span> <span class="fl">0.5</span>, <span class="kw">verbose</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">clusterAllData</span> <span class="kw">=</span> <span class="fl">FALSE</span>, <span class="kw">showPairs</span> <span class="kw">=</span> <span class="fl">FALSE</span>, <span class="kw">vxAxis</span> <span class="kw">=</span> <span class="fl">TRUE</span>)
<span class="fu"><a href="https://rdrr.io/r/grid/grid.draw.html">grid.draw</a></span>(<span class="no">retFF</span><span class="kw">[[</span><span class="st">"S1_S2_4"</span>]])</pre></body></html></div>
<div class="sourceCode" id="cb49"><html><body><pre class="r"><span class="no">retFT</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/plotClusters.html">plotClusters</a></span>(<span class="kw">dataSE</span><span class="kw">=</span><span class="no">se_soybean_cn_sub_st</span>, <span class="kw">threshVar</span><span class="kw">=</span><span class="st">"PValue"</span> ,<span class="kw">threshVal</span> <span class="kw">=</span> <span class="fl">0.05</span>, <span class="kw">nC</span> <span class="kw">=</span> <span class="fl">4</span>, <span class="kw">lineSize</span> <span class="kw">=</span> <span class="fl">0.5</span>, <span class="kw">verbose</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">clusterAllData</span> <span class="kw">=</span> <span class="fl">FALSE</span>, <span class="kw">showPairs</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">vxAxis</span> <span class="kw">=</span> <span class="fl">TRUE</span>)
<span class="fu"><a href="https://rdrr.io/r/grid/grid.draw.html">grid.draw</a></span>(<span class="no">retFT</span><span class="kw">[[</span><span class="st">"S1_S2_4"</span>]])</pre></body></html></div>
<hr>
</div>
</div>
<div id="references" class="section level2 unnumbered">
<h2 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h2>
<div id="refs" class="references">
<div id="ref-brown2015developmental">
<p>Brown, Anne V., and Karen A. Hudson. 2015. “Developmental Profiling of Gene Expression in Soybean Trifoliate Leaves and Cotyledons.” <em>BMC Plant Biology</em> 15 (1): 169.</p>
</div>
<div id="ref-Chandrasekhar">
<p>Chandrasekhar, T, K Thangavel, and E Elayaraja. 2012. “Effective Clustering Algorithms for Gene Expression Data.” <em>International Journal of Computer Applications</em> 1201: 4914.</p>
</div>
<div id="ref-soybeanIR">
<p>Lauter, AN Moran, and MA Graham. 2016. “NCBI Sra Bioproject Accession: PRJNA318409.”</p>
</div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by <a href="https://github.com/lindsayrutter">Lindsay Rutter</a>, <a href="https://github.com/dicook">Dianne Cook</a>.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.5.1.</p>
</div>

      </footer>
</div>

  
<script src="https://cdnjs.cloudflare.com/ajax/libs/docsearch.js/2.6.1/docsearch.min.js" integrity="sha256-GKvGqXDznoRYHCwKXGnuchvKSwmx9SRMrZOTh2g4Sb0=" crossorigin="anonymous"></script><script>
  docsearch({
    
    
    apiKey: 'API_KEY',
    indexName: 'INDEX_NAME',
    inputSelector: 'input#search-input.form-control',
    transformData: function(hits) {
      return hits.map(function (hit) {
        hit.url = updateHitURL(hit);
        return hit;
      });
    }
  });
</script>
</body>
</html>
