<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Data object • bigPint</title>
<!-- jquery --><script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha384-nrOSfDHtoPMzJHjVTdCopGqIqeYETSXhZDFyniQ8ZHcVy08QesyHcnOUpMpqnmWq" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/sandstone/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script><!-- Font Awesome icons --><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.7.1/clipboard.min.js" integrity="sha384-cV+rhyOuRHc9Ub/91rihWcGmMmCXDeksTtCihMupQHSsi8GIIRDG0ThDc3HGQFJ3" crossorigin="anonymous"></script><!-- sticky kit --><script src="https://cdnjs.cloudflare.com/ajax/libs/sticky-kit/1.1.3/sticky-kit.min.js" integrity="sha256-c4Rlo1ZozqTPE2RLuvbusY3+SU1pQaJC0TjuhygMipw=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><!-- docsearch --><script src="../docsearch.js"></script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css">
<link href="../docsearch.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script><meta property="og:title" content="Data object">
<meta property="og:description" content="">
<meta property="og:image" content="http://lrutter.github.io/bigPint/logo.png">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">bigPint</a>
        <span class="label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.99.0</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home"></span>
     
  </a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fas fa fas fa-book"></span>
     
    Get Started
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/plotIntro.html">Introduction to bigPint plots</a>
    </li>
    <li>
      <a href="../articles/installation.html">Installation</a>
    </li>
    <li>
      <a href="../articles/data.html">Data object</a>
    </li>
    <li>
      <a href="../articles/dataMetrics.html">Data metrics object</a>
    </li>
    <li>
      <a href="../articles/createDataMetrics.html">Creating data metrics object</a>
    </li>
    <li>
      <a href="../articles/superimposeData.html">Alternatives to data metrics object</a>
    </li>
    <li>
      <a href="../articles/static.html">Producing static plots</a>
    </li>
    <li>
      <a href="../articles/interactive.html">Producing interactive plots</a>
    </li>
    <li>
      <a href="../articles/clusters.html">Hierarchical clustering</a>
    </li>
    <li>
      <a href="../articles/pipeline.html">Recommended RNA-seq pipeline</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">
    <span class="fa fa-newspaper-o"></span>
     
    news
  </a>
</li>
<li>
  <a href="../reference/index.html">
    <span class="fa fa-file-code-o"></span>
     
    functions
  </a>
</li>
<li>
  <a href="https://github.com/lrutter/bigPint/">
    <span class="fa fa-github fa-lg"></span>
     
    github
  </a>
</li>
      </ul>
<form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="search" class="form-control" name="search-input" id="search-input" placeholder="Search..." aria-label="Search for..." autocomplete="off">
</div>
      </form>
      
    </div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Data object</h1>
                        <h4 class="author">Lindsay Rutter</h4>
                        
            <h4 class="date">2018-11-19</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/lrutter/bigPint/blob/master/vignettes/data.Rmd"><code>vignettes/data.Rmd</code></a></small>
      <div class="hidden name"><code>data.Rmd</code></div>

    </div>

    
    
<div id="about-data-object" class="section level2">
<h2 class="hasAnchor">
<a href="#about-data-object" class="anchor"></a>About data object</h2>
<p>All functions in the <code>bigPint</code> package require an input parameter called <code>data</code>, which should be a data frame that contains the full dataset of interest. If a researcher is using the package to visualize RNA-seq data, then this <code>data</code> object should be a count table that contains the read counts for all genes of interest.</p>
<hr>
</div>
<div id="example-two-treatments" class="section level2">
<h2 class="hasAnchor">
<a href="#example-two-treatments" class="anchor"></a>Example: two treatments</h2>
<p>The <code>data</code> object requires the same particular data frame format for all <code>bigPint</code> functions. There should be <span class="math inline">\(n\)</span> rows in the data frame, where <span class="math inline">\(n\)</span> is the number of genes. There should be <span class="math inline">\(p + 1\)</span> columns in the data frame, where <span class="math inline">\(p\)</span> is the number of samples. The first column contains the genes names and the rest of the columns should contain the read counts for all samples of interest. An example of this format is shown below:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw">library</span>(bigPint)</a>
<a class="sourceLine" id="cb1-2" data-line-number="2"><span class="kw">data</span>(<span class="st">"soybean_ir_sub"</span>)</a>
<a class="sourceLine" id="cb1-3" data-line-number="3"><span class="kw">head</span>(soybean_ir_sub)</a></code></pre></div>
<pre><code>##                               ID N.1 N.2 N.3 P.1 P.2 P.3
## 14881 Glyma.06G158700.Wm82.a2.v1  48  28  15  29  16   8
## 20855 Glyma.08G156000.Wm82.a2.v1   0   0   0   0   0   0
## 32104 Glyma.12G070600.Wm82.a2.v1   8  11  11   5   8   7
## 50897 Glyma.19G045200.Wm82.a2.v1 200 192 187 186 193 183
## 11303 Glyma.05G050000.Wm82.a2.v1   0   0   0   0   0   0
## 50345 Glyma.18G292300.Wm82.a2.v1 583 669 497 419 467 426</code></pre>
<p>We can also examine the structure of an example <code>data</code> object as follows:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1"><span class="kw">str</span>(soybean_ir_sub, <span class="dt">strict.width =</span> <span class="st">"wrap"</span>)</a></code></pre></div>
<pre><code>## 'data.frame':    5604 obs. of  7 variables:
## $ ID : chr "Glyma.06G158700.Wm82.a2.v1" "Glyma.08G156000.Wm82.a2.v1"
##    "Glyma.12G070600.Wm82.a2.v1" "Glyma.19G045200.Wm82.a2.v1" ...
## $ N.1: int 48 0 8 200 0 583 22 52 1 73 ...
## $ N.2: int 28 0 11 192 0 669 34 42 0 120 ...
## $ N.3: int 15 0 11 187 0 497 19 44 3 59 ...
## $ P.1: int 29 0 5 186 0 419 11 46 0 98 ...
## $ P.2: int 16 0 8 193 0 467 21 54 0 106 ...
## $ P.3: int 8 0 7 183 0 426 11 42 2 86 ...</code></pre>
<p>This example dataset contains 5,604 genes and six samples <span class="citation">(Lauter and Graham 2016)</span>. There are two treatment groups, N and P. Each treatment group contains three replicates.</p>
<hr>
</div>
<div id="data-object-rules" class="section level2">
<h2 class="hasAnchor">
<a href="#data-object-rules" class="anchor"></a>Data object rules</h2>
<p>As demonstrated above, the <code>data</code> object must meet the following conditions:</p>
<ul>
<li>Be of type <code>data.frame</code>
</li>
<li>Contain at least two treatment groups and at least two replicates per treatment group</li>
<li>Its first column must
<ul>
<li>Be called “ID”</li>
<li>Be of type <code>chr</code>
</li>
<li>Contain the names of the genes (or a unique set of names in general)</li>
</ul>
</li>
<li>Each of the rest of its columns must
<ul>
<li>Contain the read counts for a given sample (or quantitative values in general)</li>
<li>Be of type <code>int</code> or <code>num</code>
</li>
<li>Be called in a three-part format (such as “A.3”), where
<ul>
<li>The first part indicates the treatment group name and must begin with an alphabet character. Examples include “A”, “AR”, and “A9”</li>
<li>The second part consists of a dot “.” to serve as a delimeter</li>
<li>The third part indicates the replicate number and must consist of a number</li>
</ul>
</li>
</ul>
</li>
</ul>
<p>It is important that the names of all columns except the first follow the three-part format delineated above. All functions in the <code>bigPint</code> package require this format to successfully produce plots.</p>
<hr>
</div>
<div id="example-three-treatments" class="section level2">
<h2 class="hasAnchor">
<a href="#example-three-treatments" class="anchor"></a>Example: three treatments</h2>
<p>Note that the <code>data</code> object can contain more than two treatment groups. In this case, the <code>bigPint</code> software will automatically create plots for all pairs of treatment groups. An example of this type of dataset is provided in the <code>bigPint</code> package and can accessed as follows:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1"><span class="kw">data</span>(soybean_cn_sub)</a>
<a class="sourceLine" id="cb5-2" data-line-number="2"><span class="kw">str</span>(soybean_cn_sub, <span class="dt">strict.width =</span> <span class="st">"wrap"</span>)</a></code></pre></div>
<pre><code>## 'data.frame':    7332 obs. of  10 variables:
## $ ID : chr "Glyma06g12670.1" "Glyma08g12390.2" "Glyma12g02076.11"
##    "Glyma18g53450.1" ...
## $ S1.1: num 0.802 4.769 3.19 0.802 3.19 ...
## $ S1.2: num 2.709 5.236 2.902 0.802 2.48 ...
## $ S1.3: num 1.763 5.167 2.907 0.802 3.262 ...
## $ S2.1: num 7.716 3.823 3.1 0.802 0.802 ...
## $ S2.2: num 6.582 3.567 3.284 0.802 2.152 ...
## $ S2.3: num 7.004 3.296 3.296 0.802 3.93 ...
## $ S3.1: num 8.557 3.669 3.364 0.802 4.4 ...
## $ S3.2: num 8.368 4.031 2.731 0.802 3.42 ...
## $ S3.3: num 8.389 4.269 3.256 0.802 4.144 ...</code></pre>
<p>This example dataset contains 7,332 genes and nine samples <span class="citation">(Brown and Hudson 2015)</span>. There are three treatment groups, S1, S2, and S3. Each treatment group contains three replicates. In such cases where the <code>data</code> object contains more than two treatment groups, all functions in the <code>bigPint</code> package (except <code><a href="../reference/plotSMApp.html">plotSMApp()</a></code>) will automatically produce a plot for each pairwise combination of treatment groups.</p>
<p>For example, <code>bigPint</code> functions will produce plots for S1 versus S2, S1 versus S3, and S2 versus S3 in this case. The same could be accomplished (although less efficiently) by separating the dataset into three separate datasets and running a <code>bigPint</code> function of interest on each of them individually.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" data-line-number="1"><span class="kw">library</span>(dplyr)</a>
<a class="sourceLine" id="cb7-2" data-line-number="2">soybean_cn_sub_S1S2 &lt;-<span class="st"> </span>soybean_cn_sub <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="http://dplyr.tidyverse.org/reference/select.html">select</a></span>(<span class="st">"ID"</span>, <span class="kw"><a href="http://dplyr.tidyverse.org/reference/reexports.html">contains</a></span>(<span class="st">"S1"</span>), <span class="kw"><a href="http://dplyr.tidyverse.org/reference/reexports.html">contains</a></span>(<span class="st">"S2"</span>))</a>
<a class="sourceLine" id="cb7-3" data-line-number="3">soybean_cn_sub_S1S3 &lt;-<span class="st"> </span>soybean_cn_sub <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="http://dplyr.tidyverse.org/reference/select.html">select</a></span>(<span class="st">"ID"</span>, <span class="kw"><a href="http://dplyr.tidyverse.org/reference/reexports.html">contains</a></span>(<span class="st">"S1"</span>), <span class="kw"><a href="http://dplyr.tidyverse.org/reference/reexports.html">contains</a></span>(<span class="st">"S3"</span>))</a>
<a class="sourceLine" id="cb7-4" data-line-number="4">soybean_cn_sub_S2S3 &lt;-<span class="st"> </span>soybean_cn_sub <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="http://dplyr.tidyverse.org/reference/select.html">select</a></span>(<span class="st">"ID"</span>, <span class="kw"><a href="http://dplyr.tidyverse.org/reference/reexports.html">contains</a></span>(<span class="st">"S2"</span>), <span class="kw"><a href="http://dplyr.tidyverse.org/reference/reexports.html">contains</a></span>(<span class="st">"S3"</span>))</a></code></pre></div>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" data-line-number="1"><span class="kw">head</span>(soybean_cn_sub_S1S2, <span class="dv">3</span>)</a></code></pre></div>
<pre><code>##                     ID      S1.1     S1.2     S1.3     S2.1     S2.2
## 19468  Glyma06g12670.1 0.8024444 2.708884 1.763407 7.716099 6.581990
## 27284  Glyma08g12390.2 4.7687202 5.235777 5.166631 3.823472 3.566863
## 42001 Glyma12g02076.11 3.1899340 2.902131 2.906502 3.100206 3.284326
##           S2.3
## 19468 7.003538
## 27284 3.295619
## 42001 3.295619</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" data-line-number="1"><span class="kw">head</span>(soybean_cn_sub_S1S3, <span class="dv">3</span>)</a></code></pre></div>
<pre><code>##                     ID      S1.1     S1.2     S1.3     S3.1     S3.2
## 19468  Glyma06g12670.1 0.8024444 2.708884 1.763407 8.556732 8.367593
## 27284  Glyma08g12390.2 4.7687202 5.235777 5.166631 3.669489 4.031427
## 42001 Glyma12g02076.11 3.1899340 2.902131 2.906502 3.364437 2.731105
##           S3.3
## 19468 8.389347
## 27284 4.269312
## 42001 3.255649</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" data-line-number="1"><span class="kw">head</span>(soybean_cn_sub_S2S3, <span class="dv">3</span>)</a></code></pre></div>
<pre><code>##                     ID     S2.1     S2.2     S2.3     S3.1     S3.2
## 19468  Glyma06g12670.1 7.716099 6.581990 7.003538 8.556732 8.367593
## 27284  Glyma08g12390.2 3.823472 3.566863 3.295619 3.669489 4.031427
## 42001 Glyma12g02076.11 3.100206 3.284326 3.295619 3.364437 2.731105
##           S3.3
## 19468 8.389347
## 27284 4.269312
## 42001 3.255649</code></pre>
<hr>
</div>
<div id="preprocessing-of-data-object" class="section level2">
<h2 class="hasAnchor">
<a href="#preprocessing-of-data-object" class="anchor"></a>Preprocessing of data object</h2>
<p>Some popular RNA-seq analysis packages (such as <a href="https://bioconductor.org/packages/release/bioc/html/edgeR.html">edgeR</a> <span class="citation">(Robinson, McCarthy, and Smyth 2010)</span>, <a href="https://bioconductor.org/packages/release/bioc/html/DESeq2.html">DESeq2</a> <span class="citation">(Love, Huber, and Anders 2014)</span>, and <a href="https://bioconductor.org/packages/release/bioc/html/limma.html">limma</a> <span class="citation">(Ritchie et al. 2015)</span>) advise researchers to perform certain preprocessing steps to their data, such as filtering the genes, normalizing their read counts, and standardizing their read counts before visualization. Researchers can use datasets whether or not they have been filtered, normalized, and standardized for setting the <code>data</code> object in the <code>bigPint</code> package. If they wish, they can use <code>bigPint</code> plots to investigate how their dataset changes after filters, normalizations, and standardizations.</p>
<hr>
</div>
<div id="references" class="section level2 unnumbered">
<h2 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h2>
<div id="refs" class="references">
<div id="ref-brown2015developmental">
<p>Brown, Anne V., and Karen A. Hudson. 2015. “Developmental Profiling of Gene Expression in Soybean Trifoliate Leaves and Cotyledons.” <em>BMC Plant Biology</em> 15 (1). BioMed Central: 169.</p>
</div>
<div id="ref-soybeanIR">
<p>Lauter, AN Moran, and MA Graham. 2016. “NCBI Sra Bioproject Accession: PRJNA318409.”</p>
</div>
<div id="ref-love2014moderated">
<p>Love, Michael I., Wolfgang Huber, and Simon Anders. 2014. “Moderated Estimation of Fold Change and Dispersion for Rna-Seq Data with Deseq2.” <em>Genome Biology</em> 15 (12). BioMed Central: 550.</p>
</div>
<div id="ref-ritchie2015limma">
<p>Ritchie, Matthew E., Belinda Phipson, Di Wu, Yifang Hu, Charity W. Law, Wei Shi, and Gordon K. Smyth. 2015. “Limma Powers Differential Expression Analyses for Rna-Sequencing and Microarray Studies.” <em>Nucleic Acids Research</em> 43 (7). Oxford University Press: e47–e47.</p>
</div>
<div id="ref-robinson2010edger">
<p>Robinson, Mark D., Davis J. McCarthy, and Gordon K. Smyth. 2010. “EdgeR: A Bioconductor Package for Differential Expression Analysis of Digital Gene Expression Data.” <em>Bioinformatics</em> 26 (1). Oxford University Press: 139–40.</p>
</div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#about-data-object">About data object</a></li>
      <li><a href="#example-two-treatments">Example: two treatments</a></li>
      <li><a href="#data-object-rules">Data object rules</a></li>
      <li><a href="#example-three-treatments">Example: three treatments</a></li>
      <li><a href="#preprocessing-of-data-object">Preprocessing of data object</a></li>
      <li><a href="#references">References</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by <a href="https://github.com/lrutter">Lindsay Rutter</a>, <a href="https://github.com/dicook">Dianne Cook</a>.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="http://pkgdown.r-lib.org/">pkgdown</a>.</p>
</div>

      </footer>
</div>

  
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script><script>
  docsearch({
    
    
    apiKey: 'API_KEY',
    indexName: 'INDEX_NAME',
    inputSelector: 'input#search-input.form-control',
    transformData: function(hits) {
      return hits.map(function (hit) {
        hit.url = updateHitURL(hit);
        return hit;
      });
    }
  });
</script>
</body>
</html>
